version: "3.9"

services:
  service-users:
    build: ./service-users
    container_name: svc-users
    ports:
      - "5003:5000"

  service-orders:
    build: ./service-orders
    container_name: svc-orders
    ports:
      - "5004:5000"

  gateway:
    build: ./gateway
    container_name: api-gateway
    depends_on:
      - service-users
      - service-orders
    environment:
      USERS_SERVICE_URL: http://service-users:5000
      ORDERS_SERVICE_URL: http://service-orders:5000
    ports:
      - "8080:8080"