version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db-desafio3
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: desafio3db
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    container_name: cache-desafio3

  web:
    build: ./web
    container_name: web-desafio3
    depends_on:
      - db
      - cache
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: desafio3db
      DB_USER: postgres
      DB_PASSWORD: senha
      REDIS_HOST: cache
      REDIS_PORT: "6379"

volumes:
  db_data:
