version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: ms-service-a
    ports:
      - "5001:5000"

  service-b:
    build: ./service-b
    container_name: ms-service-b
    depends_on:
      - service-a
    environment:
      SERVICE_A_URL: http://service-a:5000
    ports:
      - "5002:5000"